application: hello-authsub
version: 1
api_version: 1
runtime: python

handlers:
- url: /
  script: main.py

- url: /upload
  script: upload.py

- url: /set_key
  script: set_key.py

- url: /stylesheets
  static_dir: stylesheets